### ISSUE TITLE
Error to signal on RHEL 7.6

### ISSUE THREAD

**Issue by santhosh34** [aws-cloudformation/aws-cloudformation-templates#126]
Got the following issue when i terminated instance manually to validate autoscaling creation process. 
If i shutdown one, i expected one more instance to be created. 
This script creates one more but getting following exception in logs:

$sudo grep cloud-init /var/log/messages
Output: 
+ /opt/aws/bin/cfn-signal -e 0 --stack jenkins --resource JenkinsSlaveAutoScalingGroup --region us-east-1
Dec  5 10:08:51 ip-10-80-48-198 cloud-init: ValidationError: Stack arn:aws:cloudformation:us-east-1:****:stack/jenkins/75854780-f86e-11e8-a417-*******is in CREATE_COMPLETE state and cannot be signaled

**Comment by santhosh34** [comment]
Here is the complete log:
Dec  5 11:15:33 ip-10-40-217-244 cloud-init: + /opt/aws/bin/cfn-signal -e 0 --stack adp-jenkins-agent --resource JenkinsSlaveAutoScalingGroup --region us-east-1
Dec  5 11:15:33 ip-10-40-217-244 cloud-init: ValidationError: Stack arn:aws:cloudformation:us-east-1:****:stack/adp-jenkins-agent/*****-f6ec-11e8-94f7-****** is in CREATE_COMPLETE state and cannot be signaled
Dec  5 11:15:33 ip-10-40-217-244 cloud-init: 2018-12-05 11:15:33,703 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Dec  5 11:15:33 ip-10-40-217-244 cloud-init: 2018-12-05 11:15:33,704 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Dec  5 11:15:33 ip-10-40-217-244 cloud-init: 2018-12-05 11:15:33,705 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed

**Comment by santhosh34** [comment]
The above issue is for template: awslabs/aws-cloudformation-templates/blob/master/aws/solutions/HelperNonAmaznAmi/RHEL7_cfn-hup.template

**Comment by cmmeyer** [comment]
Thanks for logging this. Let me work to get it routed to the correct owner.

**Comment by lijoantony** [comment]
@cmmeyer Any luck with this one?

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
