### ISSUE TITLE
Adding the IAM Role to an Amazon Neptune Cluster.

### ISSUE THREAD

**Issue by niroshanaj** [aws-cloudformation/aws-cloudformation-templates#153]
Hi,
please provide an example cloud-formation template to add IAM Role to an Amazon Neptune Cluster. 
Manual steps are described here:
https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-IAM.html

I would like to have this on my cloud-formation template

Thanks

**Comment by cmmeyer** [comment]
Great request. I've labeled it as an enhancement in need of an author. Thanks!

**Comment by beebs-systap** [comment]
@niroshanaj You can use the Lambda client to do this currently. Here is an [example](https://github.com/aws-samples/amazon-neptune-samples/blob/master/neptune-sagemaker/cloudformation-templates/common/add-iam-role-to-neptune.json).

**Comment by cmmeyer** [comment]
Wow! I whole pile of awesome in there, @beebs-systap!  Does that get you what you need, @niroshanaj?  

As a follow-on, we're working on a new repo that will try to aggregate links to all of these great little pockets of CloudFormation goodness. I'll make sure to put a pointer from here when it goes up.

**Comment by abdusahin** [comment]
I need feature too, looks like it's not supported by CF yet. Is there any ETA for this feature ?

**Comment by tblake84** [comment]
How is this not supported yet?  This is a key feature of neptune and is still a manual console action for end users after deploying a cloudformation template.

**Comment by harti2006** [comment]
Any news on this topic?

**Comment by namedgraph** [comment]
@beebs-systap can you please provide an update? This was reported almost 1.5 years ago.

**Comment by beebs-systap** [comment]
@namedgraph Thanks for bumping. The CFN support is there now. I'll update this thread once we have an update.

**Comment by provcristianmaluenda** [comment]
@beebs-systap Which is the new function/feature that allows us to assign a role to Neptune?
I am not a CF expert, and I am facing the same issue now. I would like to avoid to use Lambda.
Thanks!

**Comment by beebs-systap** [comment]
@provcristianmaluenda We need to push some updates on the Neptune-side to make it available. I'll update this issue.

**Comment by namedgraph** [comment]
@beebs-systap any ETA for the release?

**Comment by peterwmwong** [comment]
Any update/ETA when this will be released?

**Comment by beebs-systap** [comment]
The `AssociatedRoles` property is now supported. The documentation is rolling out over the next week.

```

DBCluster:
--
  | Type: "AWS::Neptune::DBCluster"
[snip]
  | AssociatedRoles :
  | - "arn:aws:iam::account-number:role/iam-role-name"
```

__Properties__
_AssociatedRoles_
Provides a list of the AWS Identity and Access Management (IAM) roles that are associated with the DB cluster. IAM roles that are associated with a DB cluster grant permission for the DB cluster to access other AWS services on your behalf.

__Required__: No
__Type__: List of DBClusterRole
__Update requires__: No interruption

**Comment by namedgraph** [comment]
@beebs-systap great news. Is this now in the CDK as well?

**Comment by Roshin29** [comment]
> The `AssociatedRoles` property is now supported. The documentation is rolling out over the next week.
> 
> ```
> 
> DBCluster:
> --
>   | Type: "AWS::Neptune::DBCluster"
> [snip]
>   | AssociatedRoles :
>   | - "arn:aws:iam::account-number:role/iam-role-name"
> ```
> 
> **Properties**
> _AssociatedRoles_
> Provides a list of the AWS Identity and Access Management (IAM) roles that are associated with the DB cluster. IAM roles that are associated with a DB cluster grant permission for the DB cluster to access other AWS services on your behalf.
> 
> **Required**: No
> **Type**: List of DBClusterRole
> **Update requires**: No interruption

Hi...Added Associated role in cloudformation but didnt work? can u give detail samples

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
