### ISSUE TITLE
cfnresponse.send - Response data logged to CloudWatch when "NoEcho" set

### ISSUE THREAD

**Issue by ghost** [aws-cloudformation/aws-cloudformation-templates#156]
In `cfnresponse.send`, the response data is logged to CloudWatch when `NoEcho` set to `True`.

Please see: https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py#L31

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
