### ISSUE TITLE
StackSetsResource: TemplateURL to another account and ergion

### ISSUE THREAD

**Issue by ihr** [aws-cloudformation/aws-cloudformation-templates#168]
Hi,

StackSetsResource template is really great and helps a lot, so thank you for creating it.

I would like to report a problem that I am having. I have an account "A" in a region - eu-central-1, which holds a template that is to be referenced by the StackSet Custom Resource (i.e. via the Lambda) in account 'B' in region us-west-1. I am getting this error: 

`Failed to update resource. Unexpected error: An error occurred (ValidationError) when calling the UpdateStackSet operation: Must reference a valid S3 object to which you have access. (See CloudWatch Log Stream: `

the `TemplateURL` is pointing to: `https://s3.eu-central-1.amazonaws.com/<bucket>/tempate.yaml`

I have customised the Custom Resource Lambda to use TemplateBody and I use:

      TemplateBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub 's3://${ArtifactBucket}/https-certificate.yaml'

and this works. However, there are some limitations due to using `AWS::Include`, such as one cannot use `Ref` in the `Outputs` section and also the size of the template

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
