### ISSUE TITLE
StackSetsResource: Pass Role Error on update_stack_set 

### ISSUE THREAD

**Issue by jmcguffee** [aws-cloudformation/aws-cloudformation-templates#188]
When using custom admin/execution roles there are errors updating stack sets with a PassRole permissions error. The solution to the issue is updating the update_stack_set method signature to include the admin role and execution role and follow the same strategy as create_stack_set. Attached is the code I updated to make it work in my account.
[lambda_function.py.zip](https://github.com/awslabs/aws-cloudformation-templates/files/3174337/lambda_function.py.zip)

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
