### ISSUE TITLE
cfnresponse DeprecationWarning

### ISSUE THREAD

**Issue by RutgerBeyen** [aws-cloudformation/aws-cloudformation-templates#196]
DeprecationWarning when using cfnresponse in Python Lambda:

https://pypi.org/project/cfnresponse/ with source in 'aws-cloudformation-templates/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py'

/var/task/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'. This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date. We recommend you install the requests package, 'import requests' directly, and use the requests.put() function instead.

**Comment by bobobox** [comment]
Running into this as well.

**Comment by m8786** [comment]
Started experiencing this around last Wed, Oct 2nd from the logs that I found.  We are using the cfnresponse module per instructions at: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html

**Comment by VRevol** [comment]
Hello,
I noticed that I also got this warnings in logs, will try to use import requests in cfnresponse.py lib.
Does not seem to have impacts on functionalities right now, but we also encounter some strange behaviours while using this to list/detach ENIs from lambdas on stack delete.
Might be related to the Lambda Networking changes introduced few weeks ago by AWS, or could be linked to this deprecation... not sure yet

**Comment by m8786** [comment]
I would imagine that this is supposed to be managed by AWS since they manage cfnresponse.  From the documentation, that library only functions when using the ZipFile property so I imagine they're controlling it's versioning and availability somewhere.

**Comment by VRevol** [comment]
This morning I went into more reading about usage of botocore vendored modules like requests...
For instance this article is quite insightful: https://www.serverlessops.io/blog/aws-lambda-and-python-boto3-bundling
Thus from this I believe that we should not use AWS version of botocore/boto3 nor requests and bundle ALL dependencies into our lamdba function packages.
Including rewritting cfnResponse to not use vendored requests but the official python one...

As we don't know when this deprecation will occur from AWS, I don't want to see my lambdas stopping working all a sudden...

**Comment by evannadeau** [comment]
Warning to all, this has been coming for some time apparently, and we are rushing to remove our use of botocore vendored requests module as the commit to remove it is happening October 21st.  We have created a layer shared to our org that contains "Requests", adding this to functions and then just replace the appropriate lines of code.

Layer added to lambda:
`Layers:
      - !Sub 'arn:aws:lambda:${AWS::Region}:1234567890:layer:Requests:1'`

Python code before:
`from botocore.vendored import requests`
Python code after:
`import requests`

[https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/](https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/)

[https://github.com/boto/botocore/pull/1829](https://github.com/boto/botocore/pull/1829)

We currently do our CFN respones inline, and would like to remove this by using the AWS cfnresponse module, but sadly I see that they are using the botocore.vendored requests module as well.

**Comment by gmagella-ca** [comment]
This issue was closed with the other one, and no solution has been implemented. There's a deadline to implement changes from the message:

> This dependency was removed from Botocore and will be removed from Lambda after 2020/03/31.

Can we get this re-opened?

**Comment by gmagella-ca** [comment]
Nevermind, this one is not closed, my bad :)

**Comment by VRevol** [comment]
We did the same way as @evannadeau implementing Requests as a layer. We even implement cfnresponse as another layer, and import both of them in our lambdas.

Only drawback, we should maintain the Requests layer and update it from time to time as layers are static. New versions should be created as main code is released.

**Comment by ikben** [comment]
See also this issue in the coverage roadmap: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/246

**Comment by alanivey** [comment]
Is there a way to use `ZipFile` and have the function import cfnresponse without the aforementioned cfnresponse.py being included? I want to update my custom resources to use my edited versions of cfnresponse.py with urllib2/3 via layers, but so far I have only been able to get around this by minifying+compressing the code first.

**Comment by wcurudy** [comment]
I also ran into this; it occurred to me that while this is an annoyance for my own usecase (I've made a requests layer), an awful lot of AWS quickstarts and online examples use cfnresponse with inline functions, and would presumably be broken once the deprecation is finalized. Or is AWS planning to fix cfnresponse somehow? Is there any way to replicate cfnresponse functionality with an inline function?

Obviously it's better to manage/package your own dependencies but...well, code monkey see, code monkey do.

**Comment by alanivey** [comment]
Here's my workaround, which I strongly dislike, because CloudFormation has seen my attempts to use `import cfnresponse`, `import boto3, cfnresponse`, etc, and bundles the file for me. I thought the latter worked before (years ago), but it makes sense so various guides and folks applying lessons from them have the documented behaviour. Until something better comes along, I hope this helps others:

```bash
for FUNCTION in CfnNatInit CfnVpcInit ; do
  CODE_MINIFIED="$( cfn-flip --json "../templates/LambdaCfnHelpers/$FUNCTION.yaml" | jq -r '.Resources.LambdaFunction.Properties.Code.ZipFile' | pyminifier --gzip /dev/stdin )"

  TEMPLATE_WITH_CODE_MINIFIED="$( cfn-flip --json "../templates/LambdaCfnHelpers/$FUNCTION.yaml" | jq --arg code "$CODE_MINIFIED" '.Resources.LambdaFunction.Properties.Code.ZipFile = $code' | cfn-flip --yaml )"

  aws cloudformation update-stack-set \
    --stack-set-name "$FUNCTION" \
    --cli-input-json "$( aws cloudformation validate-template --template-body "file://../templates/LambdaCfnHelpers/${FUNCTION}.yaml" --output 'json' | jq -cM '{Description:.Description,Capabilities:.Capabilities}' )" \
    --template-body "$TEMPLATE_WITH_CODE_MINIFIED" \
    --operation-preferences 'RegionOrder=us-east-1,MaxConcurrentPercentage=100'
done
```

**Comment by mengmann** [comment]
Come on. This is so easy to fix for AWS, just swap deprecated botocore.vendored.requests by native python module urllib3. Thanks to @chapmancl, now we have an updated example cfnresponse.py for those who bundle their function code with static dependencies. But there are still a lot people outside who deliver their small Python Code inline with CloudFormation and rely on generic added cfnresponse.py in Lambda.
At least AWS has extended the deadline **until 2021** by now.

> /var/runtime/botocore/vendored/requests/api.py:64: DeprecationWarning: You are using the put() function from 'botocore.vendored.requests'. This dependency was removed from Botocore and will be removed from Lambda after 2021/01/30. https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/. Install the requests package, 'import requests' directly, and use the requests.put() function instead.

**Comment by zanderz** [comment]
Even worse, AWS's own documentation says "This is the cfnresponse source code provided in the runtime" and shows the updated version (without vendored requests): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html

but when your lambda gets created and you look in the dashboard, you can click on the cfnresponse module provided by them in the runtime it is still the old code with the vendored requests import.

**Comment by mengmann** [comment]
Finally solved by AWS. 

> To update the cfn-response module to the latest version that uses urllib3, update the function’s inline code in the AWS CloudFormation template by adding a comment to the inline Lambda function's code. 

Source: https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-cfn-response-lambda/
