### ISSUE TITLE
Accounts starting with 0 are incorrectly transformed by cloudformation package

### ISSUE THREAD

**Issue by mcmurm** [aws-cloudformation/aws-cloudformation-templates#210]
StackInstances list that contains an Account starting with the integer 0 causes an error due to improperly being transformed by aws cloudformation package.

Example:
`                "StackInstances": [
                    {
                        "Accounts": [
                            "248234381465",
                            "774157840904"
                        ],
                        "Regions": [
                            "us-east-1"
                        ]
                    },
                    {
                        "Accounts": [
                            "774157840904"
                        ],
                        "Regions": [
                            "us-west-2"
                        ]
                    },
                    {
                        "Accounts": [
                            "081137507012"
                        ],
                        "Regions": [
                            "ap-southeast-2"
                        ]
                    }
                ]`

After packaged, results in:

`      StackInstances:
      - Accounts:
        - '248234381465'
        - '774157840904'
        Regions:
        - us-east-1
      - Accounts:
        - '774157840904'
        Regions:
        - us-west-2
      - Accounts:
        - 081137507012
        Regions:
        - ap-southeast-2
`

After deployment, Lambda throws this error:

`botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStackInstances operation: 1 validation error detected: Value '[8.1137507012E10]' at 'accounts' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9]{12}]`

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
