### ISSUE TITLE
WordPress template not working with modern wordpress. Missing default redirect.

### ISSUE THREAD

**Issue by macetw** [aws-cloudformation/aws-cloudformation-templates#214]
Using the current WordPress template, the Yum packages defined in the template are not working with the most recent code of wordpress. This updates those libraries to work with them correctly. MySQL and PHP needs package reference updates.

There's also a security precaution that it is missing a basic "yum update" for any other updates on packages.

Also, the default behavior leaves the web site with a default apache welcome page, which is not helpful.

**Comment by ericzbeard** [comment]
Cleaning up stale issues in preparation for refreshing this repository. Please re-open if this still needs to be addressed.
