### ISSUE TITLE
Including port 443 for HTTPS

### ISSUE THREAD

**Issue by markentingh** [aws-cloudformation/aws-cloudformation-templates#233]
Can you include port 443 for HTTPS traffic in your examples, which is the standard for web hosting.

**Comment by nranpura** [comment]
Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http and https to client host
      GroupName: "security-group-name"
      VpcId: !Ref VPC
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIpv6: ::/0
