### ISSUE TITLE
Issues in ASG creation 

### ISSUE THREAD

**Issue by kozharsky** [aws-cloudformation/aws-cloudformation-templates#247]
I tried to create this tempalte `AutoScaling/AutoScalingMultiAZWithNotifications.yaml` in this repo, and I always get this issue  in ASG creation ```Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement```

Can you take a look on this
I tested in Oregon btw

Thanks

**Comment by chinnshan** [comment]
I suggest you try to login to the instance while it is still up and running and check for a service that is still not fully up. I guess, PT15M gives you sufficient time for that.
