### ISSUE TITLE
No export named production:ECSTaskExecutionRole found. Rollback requested by user.

### ISSUE THREAD

**Issue by KijanaG** [aws-cloudformation/aws-cloudformation-templates#263]
When creating a stack in CloudFormation, I continually get the error: "No export named production:[ECSTaskExecutionRole] found. Rollback requested by user." Where ECSTaskExecutionRole can be one of the many Import Values for the private-subnet-private-service.yml CloudFormation FarGate template.

**Comment by treerao** [comment]
Two likely possibilities (assuming 0. you executed the cluster stack first) based on my experience hitting this error using these templates just now:

1. Stack name for the cluster needs to be set in the service yml ("production" is the default value in there)
2. Need to wait for the cluster stack to complete
