### ISSUE TITLE
Received malformed response from transform 863829428800::S3Objects

### ISSUE THREAD

**Issue by irfaanz** [aws-cloudformation/aws-cloudformation-templates#267]
Hello,

I followed the steps outlined by Steve Engledow, and I am testing out the S3 Object Macro. 
[https://github.com/awslabs/aws-cloudformation-templates/commit/ef4022110d67015e0a3167d707c45d08dc0f587b](url) when i am trying out the third command "aws cloudformation deploy \
    --stack-name s3objects-macro-example \
    --template-file example.template \
    --capabilities CAPABILITY_IAM"

I keep getting the error that " Received malformed response from transform 863829428800::S3Objects." I dont know why this is happening, and i m unable to test this macro function which i wanted to add in my CFN template. I would greatly appreciate if you can look into this and guide me further.

Irfan

**Comment by stilvoid** [comment]
Hi @irfaanz if you check the CloudWatch logs for the S3Object macro function, you will find more detail. You can find out which Lambda function it is by checking the CloudFormation stack you launched in step 3, `s3objects-macro`.

**Comment by sl-omideidivandi** [comment]
I had the same problem and just that vas env var missing

**Comment by irfaanz** [comment]
> Hi @irfaanz if you check the CloudWatch logs for the S3Object macro function, you will find more detail. You can find out which Lambda function it is by checking the CloudFormation stack you launched in step 3, `s3objects-macro`.

Thanks for the help. I am sorry, i had other things to take care due to global pandemic and i was unable to test it, I truly appreciate your help. I will check and keep you updated. 

Irfan

**Comment by irfaanz** [comment]
> I had the same problem and just that vas env var missing

Could you guide me how you resolved with clear steps to follow, i would greatly appreciate it. 

Irfan

**Comment by irfaanz** [comment]
> Hi @irfaanz if you check the CloudWatch logs for the S3Object macro function, you will find more detail. You can find out which Lambda function it is by checking the CloudFormation stack you launched in step 3, `s3objects-macro`.

This is from the logs "

2020-07-01T02:33:55.409+05:30 | Syntax error in module 'macro': invalid syntax (macro.py, line 6)
-- | --
  | 2020-07-01T02:33:55.409+05:30 | END RequestId: 31383859-c531-459e-bfe2-cd1217cb278c
  | 2020-07-01T02:33:55.409+05:30 | REPORT RequestId: 31383859-c531-459e-bfe2-cd1217cb278c Duration: 0.43 ms Billed Duration
That is the log for the same macro that i deployed today and tried follow the steps from that link. 
"
