### ISSUE TITLE
easy_install removed from python-setuptools so breaking cfn-hup setups

### ISSUE THREAD

**Issue by grahamjenson** [aws-cloudformation/aws-cloudformation-templates#272]
The package easy_install was removed from the apt package as shown by this changelog https://launchpad.net/ubuntu/+source/python-setuptools/39.0.1-2

This breaks scripts like:
https://github.com/awslabs/aws-cloudformation-templates/blob/b50886cb572604fa57fff0f628e1c7f3851b9a69/aws/solutions/HelperNonAmaznAmi/ubuntu16.04LTS_cfn-hup.template#L121

**Comment by toknlster2020** [comment]
I think you can use below command to replace it. 
python -m easy_install --script-dir /opt/aws/bin aws-cfn-bootstrap-latest.tar.gz

**Comment by jesusaurus** [comment]
What prevents migration from easy_install to pip?

https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
