### ISSUE TITLE
easy_install is not in python-pip package for Ubuntu 18.04

### ISSUE THREAD

**Issue by sebawagner** [aws-cloudformation/aws-cloudformation-templates#283]
See also: https://bugs.launchpad.net/ubuntu/+source/python-setuptools/+bug/1774419

So running this with Ubuntu 18.04 LTS will result in easy_install command not found.

This script will fail:
https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/AmazonCloudWatchAgent/inline/ubuntu.template#L137

**Comment by TheSwede86** [comment]
I also came across this trying to get 18.04 to work, I believe a workaround can be found here:
`
sudo apt-get update -y
sudo apt-get install python-pip -y
sudo pip2 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
`
found that here:
https://github.com/aws-quickstart/quickstart-linux-utilities/blob/main/quickstart-cfn-tools.source#L290

Seems like a good project in general to make it easier to work with bootstrapping in CF.
