### ISSUE TITLE
Update python version for boto3 macro 

### ISSUE THREAD

**Issue by zaro0508** [aws-cloudformation/aws-cloudformation-templates#340]
The boto3 macro is [setup with python2.7](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/Boto3/macro.template#L7) which is EOL and not even supported by SAM any longer which means it will fail to deploy to AWS.  Would be great if this macro can be updated with a newer supported version of python.  

```
AWS CloudFormation Linter................................................Failed

- hook id: cfn-python-lint

- exit code: 2

E2531 Deprecated runtime (python2.7) specified. Updating disabled since 2021-09-30. Please consider updating to python3.8

template.yaml:5:3
```

**Comment by zoellner** [comment]
same for the S3Objects marcro at `aws-cloudformation-templates/aws/services/CloudFormation/MacrosExamples/S3Objects/macro.template`
