### ISSUE TITLE
cfnresponse.py squelching errors

### ISSUE THREAD

**Issue by hauntingEcho** [aws-cloudformation/aws-cloudformation-templates#342]
Currently, cfnresource.py simply [logs a message and does not throw errors up to its calling code](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py#L39), meaning that resources cannot react to these failure.

**Comment by chiranshu2** [comment]
Majorly sending failure requests
