### ISSUE TITLE
cfnresponse.py helper does not accept "Reason" parameter

### ISSUE THREAD

**Issue by SHxKM** [aws-cloudformation/aws-cloudformation-templates#352]
The `send` function signature:

https://github.com/awslabs/aws-cloudformation-templates/blob/2415d1dd34bdbf50e3b009879f6ba754a043afdf/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py#L10

Does not allow its caller to pass a `Reason`, which according to [AWS' documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html) is **required** if the status is `FAIL`. Instead, [it always returns a very generic and less useful message](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py#L17).

Is there any reason for this?

**Comment by kubo1060** [comment]
This could be really helpful improvement, i dont understand why its not there yet..
